const menus = [
  {
    gender: "men",
    category: "Featured",
    tags: [
      "New Releases",
      "Bestsellers",
      "Member Exclusive",
      "Jordan",
      "Retro Running",
      "Customise with Nike By You",
      "Sale",
      "Running Shoe Finder",
      "Sustainable Materials",
    ],
  },
  {
    gender: "men",
    category: "Jordan",
    tags: [
      "All Jordan",
      "New Jordan",
      "Jordan Shoes",
      "Jordan Clothing",
      "Jordan Basketball",
      "Jordan Lifestyle",
    ],
  },
  {
    gender: "men",
    category: "Shoes",
    tags: [
      "All Shoes",
      "Newest Sneakers",
      "Jordan",
      "Lifestyle",
      "Running",
      "Gym and Training",
      "Basketball",
      "Football",
      "Sandals and Slides",
      "Last Sizes Available",
    ],
  },
  {
    gender: "men",
    category: "Clothing",
    tags: [
      "All Clothing",
      "Tops and T-Shirts",
      "Shorts",
      "Pants and Leggings",
      "Hoodies and Sweatshirts",
      "Jackets and Gilets",
      "Jerseys and Kits",
      "Jordan",
    ],
  },
  {
    gender: "men",
    category: "Accessories and Equipment",
    tags: [
      "All Accessories and Equipment",
      "Bags and Backpacks",
      "Socks",
      "Hats and Headwear",
    ],
  },
  {
    gender: "men",
    category: "Shop By Sport",
    tags: [
      "Running",
      "Football",
      "Basketball",
      "Gym and Training",
      "Yoga",
      "Skateboarding",
      "Tennis",
      "Golf",
    ],
  },
  {
    gender: "men",
    category: "Shop By Brand",
    tags: [
      "Nike Sportwear",
      "NikeLab",
      "Nike By You",
      "Jordan",
      "ACG",
      "NBA",
      "Nike SB",
    ],
  },
  {
    gender: "women",
    category: "Accessories and Equipment",
    tags: [
      "All Accessories and Equipment",
      "Bags and Backpacks",
      "Socks",
      "Hats and Headwear",
    ],
  },
];

export { menus };
