const products = [
  {
    id: 1,
    gender: "men",
    name: "Nike Air Force 1 '07",
    des: "Iconic men's sneakers for a timeless style",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "black",
    size_UK: [7, 8, 9, 10],
    price: 100,
    image: "Image_URL_1",
  },
  {
    id: 2,
    gender: "men",
    name: "Nike Air Max 90",
    des: "Classic men's sneakers with iconic Air Max cushioning",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "white",
    size_UK: [7, 8, 9, 10],
    price: 120,
    image: "Image_URL_2",
  },
  {
    id: 3,
    gender: "women",
    name: "Nike React Infinity Run Flyknit",
    des: "Women's running shoes with responsive cushioning",
    category: "shoes",
    tag: ["Running"],
    color: "blue",
    size_UK: [5, 6, 7, 8],
    price: 150,
    image: "Image_URL_3",
  },
  {
    id: 4,
    gender: "men",
    name: "Nike Zoom Freak 3",
    des: "Men's basketball shoes designed for speed and power",
    category: "shoes",
    tag: ["Basketball"],
    color: "red",
    size_UK: [8, 9, 10, 11],
    price: 130,
    image: "Image_URL_4",
  },
  {
    id: 5,
    gender: "unisex",
    name: "Nike Air Zoom Pegasus 38",
    des: "Versatile shoes offering comfort and stability",
    category: "shoes",
    tag: ["Running"],
    color: "grey",
    size_UK: [6, 7, 8, 9],
    price: 140,
    image: "Image_URL_5",
  },
  {
    id: 6,
    gender: "unisex",
    name: "Nike Sportswear Club Fleece Hoodie",
    des: "Classic fleece hoodie for warmth and comfort",
    category: "clothing",
    tag: ["Hoodies & Sweatshirts"],
    color: "black",
    size_UK: ["S", "M", "L", "XL"],
    price: 80,
    image: "Image_URL_6",
  },
  {
    id: 7,
    gender: "women",
    name: "Nike Pro Women's 3\" Shorts",
    des: "Comfortable and supportive training shorts",
    category: "clothing",
    tag: ["Shorts"],
    color: "pink",
    size_UK: ["XS", "S", "M", "L"],
    price: 45,
    image: "Image_URL_7",
  },
  {
    id: 8,
    gender: "men",
    name: "Nike SB Check Solarsoft Skateboarding Shoes",
    des: "Durable and comfortable skateboarding shoes",
    category: "shoes",
    tag: ["Skateboarding"],
    color: "black",
    size_UK: [8, 9, 10, 11],
    price: 85,
    image: "Image_URL_8",
  },
  {
    id: 9,
    gender: "unisex",
    name: "Nike Court Vision Low",
    des: "Classic low-top sneakers for versatile wear",
    category: "shoes",
    tag: ["Tennis"],
    color: "white",
    size_UK: [6, 7, 8, 9],
    price: 75,
    image: "Image_URL_9",
  },
  {
    id: 10,
    gender: "men",
    name: "Nike Air Zoom Infinity Tour Golf Shoes",
    des: "Golf shoes designed for stability and comfort",
    category: "shoes",
    tag: ["Golf"],
    color: "grey",
    size_UK: [7, 8, 9, 10],
    price: 200,
    image: "Image_URL_10",
  },
  {
    id: 11,
    gender: "men",
    name: "Nike Air Force 1 '07",
    des: "Iconic men's sneakers for a timeless style",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "white",
    size_UK: [7, 8, 9, 10],
    price: 110,
    image: "Image_URL_11",
  },
  {
    id: 12,
    gender: "women",
    name: "Nike React Infinity Run Flyknit",
    des: "Women's running shoes with responsive cushioning",
    category: "shoes",
    tag: ["Running"],
    color: "black",
    size_UK: [5, 6, 7, 8],
    price: 160,
    image: "Image_URL_12",
  },
  {
    id: 13,
    gender: "men",
    name: "Nike Air Max 90",
    des: "Classic men's sneakers with iconic Air Max cushioning",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "grey",
    size_UK: [7, 8, 9, 10],
    price: 125,
    image: "Image_URL_13",
  },
  {
    id: 14,
    gender: "men",
    name: "Nike Zoom Freak 3",
    des: "Men's basketball shoes designed for speed and power",
    category: "shoes",
    tag: ["Basketball"],
    color: "black",
    size_UK: [8, 9, 10, 11],
    price: 135,
    image: "Image_URL_14",
  },
  {
    id: 15,
    gender: "unisex",
    name: "Nike Air Zoom Pegasus 38",
    des: "Versatile shoes offering comfort and stability",
    category: "shoes",
    tag: ["Running"],
    color: "red",
    size_UK: [6, 7, 8, 9],
    price: 145,
    image: "Image_URL_15",
  },
  {
    id: 16,
    gender: "unisex",
    name: "Nike Sportswear Club Fleece Hoodie",
    des: "Classic fleece hoodie for warmth and comfort",
    category: "clothing",
    tag: ["Hoodies & Sweatshirts"],
    color: "grey",
    size_UK: ["S", "M", "L", "XL"],
    price: 85,
    image: "Image_URL_16",
  },
  {
    id: 17,
    gender: "women",
    name: "Nike Pro Women's 3\" Shorts",
    des: "Comfortable and supportive training shorts",
    category: "clothing",
    tag: ["Shorts"],
    color: "blue",
    size_UK: ["XS", "S", "M", "L"],
    price: 50,
    image: "Image_URL_17",
  },
  {
    id: 18,
    gender: "men",
    name: "Nike SB Check Solarsoft Skateboarding Shoes",
    des: "Durable and comfortable skateboarding shoes",
    category: "shoes",
    tag: ["Skateboarding"],
    color: "green",
    size_UK: [8, 9, 10, 11],
    price: 90,
    image: "Image_URL_18",
  },
  {
    id: 19,
    gender: "unisex",
    name: "Nike Court Vision Low",
    des: "Classic low-top sneakers for versatile wear",
    category: "shoes",
    tag: ["Tennis"],
    color: "yellow",
    size_UK: [6, 7, 8, 9],
    price: 80,
    image: "Image_URL_19",
  },
  {
    id: 20,
    gender: "men",
    name: "Nike Air Zoom Infinity Tour Golf Shoes",
    des: "Golf shoes designed for stability and comfort",
    category: "shoes",
    tag: ["Golf"],
    color: "orange",
    size_UK: [7, 8, 9, 10],
    price: 210,
    image: "Image_URL_20",
  },
  {
    id: 21,
    gender: "women",
    name: "Nike Air Force 1 '07",
    des: "Iconic women's sneakers for a timeless style",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "pink",
    size_UK: [5, 6, 7, 8],
    price: 95,
    image: "Image_URL_21",
  },
  {
    id: 22,
    gender: "men",
    name: "Nike Air Max 90",
    des: "Men's sneakers with iconic Air Max cushioning",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "blue",
    size_UK: [7, 8, 9, 10],
    price: 130,
    image: "Image_URL_22",
  },
  {
    id: 23,
    gender: "men",
    name: "Nike Zoom Freak 3",
    des: "Men's basketball shoes designed for speed and power",
    category: "shoes",
    tag: ["Basketball"],
    color: "purple",
    size_UK: [8, 9, 10, 11],
    price: 140,
    image: "Image_URL_23",
  },
  {
    id: 24,
    gender: "unisex",
    name: "Nike Air Zoom Pegasus 38",
    des: "Versatile shoes offering comfort and stability",
    category: "shoes",
    tag: ["Running"],
    color: "green",
    size_UK: [6, 7, 8, 9],
    price: 150,
    image: "Image_URL_24",
  },
  {
    id: 25,
    gender: "unisex",
    name: "Nike Sportswear Club Fleece Hoodie",
    des: "Classic fleece hoodie for warmth and comfort",
    category: "clothing",
    tag: ["Hoodies & Sweatshirts"],
    color: "brown",
    size_UK: ["S", "M", "L", "XL"],
    price: 90,
    image: "Image_URL_25",
  },
  {
    id: 26,
    gender: "women",
    name: "Nike Pro Women's 3\" Shorts",
    des: "Comfortable and supportive training shorts",
    category: "clothing",
    tag: ["Shorts"],
    color: "red",
    size_UK: ["XS", "S", "M", "L"],
    price: 55,
    image: "Image_URL_26",
  },
  {
    id: 27,
    gender: "men",
    name: "Nike SB Check Solarsoft Skateboarding Shoes",
    des: "Durable and comfortable skateboarding shoes",
    category: "shoes",
    tag: ["Skateboarding"],
    color: "multi-color",
    size_UK: [8, 9, 10, 11],
    price: 95,
    image: "Image_URL_27",
  },
  {
    id: 28,
    gender: "unisex",
    name: "Nike Court Vision Low",
    des: "Classic low-top sneakers for versatile wear",
    category: "shoes",
    tag: ["Tennis"],
    color: "yellow",
    size_UK: [6, 7, 8, 9],
    price: 85,
    image: "Image_URL_28",
  },
  {
    id: 29,
    gender: "men",
    name: "Nike Air Zoom Infinity Tour Golf Shoes",
    des: "Golf shoes designed for stability and comfort",
    category: "shoes",
    tag: ["Golf"],
    color: "orange",
    size_UK: [7, 8, 9, 10],
    price: 220,
    image: "Image_URL_29",
  },
  {
    id: 30,
    gender: "women",
    name: "Nike Air Force 1 '07",
    des: "Iconic women's sneakers for a timeless style",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "white",
    size_UK: [5, 6, 7, 8],
    price: 105,
    image: "Image_URL_30",
  },
  {
    id: 31,
    gender: "men",
    name: "Nike Air Max 270",
    des: "Men's lifestyle shoes with Max Air cushioning",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "black",
    size_UK: [7, 8, 9, 10],
    price: 150,
    image: "Image_URL_31",
  },
  {
    id: 32,
    gender: "women",
    name: "Nike Air Zoom Pegasus 38",
    des: "Women's versatile running shoes with Zoom Air unit",
    category: "shoes",
    tag: ["Running"],
    color: "purple",
    size_UK: [5, 6, 7, 8],
    price: 160,
    image: "Image_URL_32",
  },
  {
    id: 33,
    gender: "men",
    name: "Nike React Element 55",
    des: "Men's lifestyle shoes with React foam cushioning",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "blue",
    size_UK: [7, 8, 9, 10],
    price: 130,
    image: "Image_URL_33",
  },
  {
    id: 34,
    gender: "men",
    name: "Nike Air Force 1 Low",
    des: "Men's iconic sneakers with premium leather",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "white",
    size_UK: [7, 8, 9, 10],
    price: 120,
    image: "Image_URL_34",
  },
  {
    id: 35,
    gender: "women",
    name: "Nike Free RN 5.0",
    des: "Women's minimalist running shoes for a natural feel",
    category: "shoes",
    tag: ["Running"],
    color: "pink",
    size_UK: [5, 6, 7, 8],
    price: 110,
    image: "Image_URL_35",
  },
  {
    id: 36,
    gender: "unisex",
    name: "Nike Benassi Slide",
    des: "Unisex slides for casual wear and comfort",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "black",
    size_UK: [6, 7, 8, 9],
    price: 30,
    image: "Image_URL_36",
  },
  {
    id: 37,
    gender: "men",
    name: "Nike Air Zoom Structure 24",
    des: "Men's running shoes with stability and support",
    category: "shoes",
    tag: ["Running"],
    color: "grey",
    size_UK: [7, 8, 9, 10],
    price: 140,
    image: "Image_URL_37",
  },
  {
    id: 38,
    gender: "women",
    name: "Nike Blazer Low",
    des: "Women's vintage-style sneakers with suede upper",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "red",
    size_UK: [5, 6, 7, 8],
    price: 100,
    image: "Image_URL_38",
  },
  {
    id: 39,
    gender: "men",
    name: "Nike Air Max Plus",
    des: "Men's athletic shoes with Tuned Air cushioning",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "yellow",
    size_UK: [7, 8, 9, 10],
    price: 170,
    image: "Image_URL_39",
  },
  {
    id: 40,
    gender: "women",
    name: "Nike React Infinity Run Flyknit",
    des: "Women's running shoes with responsive cushioning",
    category: "shoes",
    tag: ["Running"],
    color: "green",
    size_UK: [5, 6, 7, 8],
    price: 160,
    image: "Image_URL_40",
  },
  {
    id: 41,
    gender: "men",
    name: "Nike Air Max 97",
    des: "Men's lifestyle shoes with iconic design",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "grey",
    size_UK: [7, 8, 9, 10],
    price: 180,
    image: "Image_URL_41",
  },
  {
    id: 42,
    gender: "women",
    name: "Nike Air Zoom Vomero 16",
    des: "Women's cushioned running shoes for long-distance comfort",
    category: "shoes",
    tag: ["Running"],
    color: "purple",
    size_UK: [5, 6, 7, 8],
    price: 170,
    image: "Image_URL_42",
  },
  {
    id: 43,
    gender: "men",
    name: "Nike React Presto",
    des: "Men's lifestyle shoes offering lightweight comfort",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "blue",
    size_UK: [7, 8, 9, 10],
    price: 140,
    image: "Image_URL_43",
  },
  {
    id: 44,
    gender: "men",
    name: "Nike Air Force 1 LV8",
    des: "Men's iconic sneakers with premium details",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "white",
    size_UK: [7, 8, 9, 10],
    price: 130,
    image: "Image_URL_44",
  },
  {
    id: 45,
    gender: "women",
    name: "Nike Air Zoom Structure 24",
    des: "Women's running shoes with stability and support",
    category: "shoes",
    tag: ["Running"],
    color: "pink",
    size_UK: [5, 6, 7, 8],
    price: 150,
    image: "Image_URL_45",
  },
  {
    id: 46,
    gender: "unisex",
    name: "Nike Benassi JDI",
    des: "Unisex slides for casual wear and comfort",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "black",
    size_UK: [6, 7, 8, 9],
    price: 25,
    image: "Image_URL_46",
  },
  {
    id: 47,
    gender: "men",
    name: "Nike Air Max 2090",
    des: "Men's futuristic lifestyle shoes with Air cushioning",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "grey",
    size_UK: [7, 8, 9, 10],
    price: 160,
    image: "Image_URL_47",
  },
  {
    id: 48,
    gender: "women",
    name: "Nike Air Max Excee",
    des: "Women's lifestyle shoes inspired by the '90s",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "red",
    size_UK: [5, 6, 7, 8],
    price: 120,
    image: "Image_URL_48",
  },
  {
    id: 49,
    gender: "men",
    name: "Nike Renew Run 2",
    des: "Men's running shoes for a smooth and cushioned ride",
    category: "shoes",
    tag: ["Running"],
    color: "green",
    size_UK: [7, 8, 9, 10],
    price: 140,
    image: "Image_URL_49",
  },
  {
    id: 50,
    gender: "women",
    name: "Nike Air Force 1 Pixel",
    des: "Women's modern sneakers with exaggerated details",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "white",
    size_UK: [5, 6, 7, 8],
    price: 135,
    image: "Image_URL_50",
  },
  {
    id: 51,
    gender: "men",
    name: "Nike Air Max 95",
    des: "Men's lifestyle shoes with retro design",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "black",
    size_UK: [7, 8, 9, 10],
    price: 170,
    image: "Image_URL_51",
  },
  {
    id: 52,
    gender: "women",
    name: "Nike Air Zoom Terra Kiger 7",
    des: "Women's trail running shoes with responsive cushioning",
    category: "shoes",
    tag: ["Running"],
    color: "orange",
    size_UK: [5, 6, 7, 8],
    price: 180,
    image: "Image_URL_52",
  },
  {
    id: 53,
    gender: "men",
    name: "Nike React Vision",
    des: "Men's lifestyle shoes with futuristic design",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "white",
    size_UK: [7, 8, 9, 10],
    price: 150,
    image: "Image_URL_53",
  },
  {
    id: 54,
    gender: "men",
    name: "Nike Air Force 1 High '07",
    des: "Men's iconic high-top sneakers with classic design",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "blue",
    size_UK: [7, 8, 9, 10],
    price: 140,
    image: "Image_URL_54",
  },
  {
    id: 55,
    gender: "women",
    name: "Nike React Miler 2",
    des: "Women's running shoes with cushioned support",
    category: "shoes",
    tag: ["Running"],
    color: "pink",
    size_UK: [5, 6, 7, 8],
    price: 130,
    image: "Image_URL_55",
  },
  {
    id: 56,
    gender: "unisex",
    name: "Nike Benassi JDI Print",
    des: "Unisex slides with printed strap for casual wear",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "black",
    size_UK: [6, 7, 8, 9],
    price: 35,
    image: "Image_URL_56",
  },
  {
    id: 57,
    gender: "men",
    name: "Nike Air Max Plus III",
    des: "Men's lifestyle shoes with Tuned Air cushioning",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "grey",
    size_UK: [7, 8, 9, 10],
    price: 190,
    image: "Image_URL_57",
  },
  {
    id: 58,
    gender: "women",
    name: "Nike Air Max 200",
    des: "Women's lifestyle shoes with Max Air cushioning",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "red",
    size_UK: [5, 6, 7, 8],
    price: 125,
    image: "Image_URL_58",
  },
  {
    id: 59,
    gender: "men",
    name: "Nike Downshifter 11",
    des: "Men's running shoes for everyday runs",
    category: "shoes",
    tag: ["Running"],
    color: "green",
    size_UK: [7, 8, 9, 10],
    price: 90,
    image: "Image_URL_59",
  },
  {
    id: 60,
    gender: "women",
    name: "Nike Air Max Verona",
    des: "Women's lifestyle shoes inspired by '90s Air Max",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "white",
    size_UK: [5, 6, 7, 8],
    price: 140,
    image: "Image_URL_60",
  },
  {
    id: 61,
    gender: "men",
    name: "Nike Air Max 2090",
    des: "Men's lifestyle shoes with futuristic design",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "black",
    size_UK: [7, 8, 9, 10],
    price: 160,
    image: "Image_URL_61",
  },
  {
    id: 62,
    gender: "women",
    name: "Nike Air Zoom Winflo 8",
    des: "Women's running shoes with responsive cushioning",
    category: "shoes",
    tag: ["Running"],
    color: "blue",
    size_UK: [5, 6, 7, 8],
    price: 120,
    image: "Image_URL_62",
  },
  {
    id: 63,
    gender: "men",
    name: "Nike Revolution 5",
    des: "Men's running shoes for cushioned comfort",
    category: "shoes",
    tag: ["Running"],
    color: "grey",
    size_UK: [7, 8, 9, 10],
    price: 65,
    image: "Image_URL_63",
  },
  {
    id: 64,
    gender: "men",
    name: "Nike Air Force 1 '07",
    des: "Men's iconic sneakers with classic design",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "white",
    size_UK: [7, 8, 9, 10],
    price: 100,
    image: "Image_URL_64",
  },
  {
    id: 65,
    gender: "women",
    name: "Nike Free RN 5.0",
    des: "Women's minimalist running shoes for natural feel",
    category: "shoes",
    tag: ["Running"],
    color: "pink",
    size_UK: [5, 6, 7, 8],
    price: 110,
    image: "Image_URL_65",
  },
  {
    id: 66,
    gender: "unisex",
    name: "Nike Benassi Slide",
    des: "Unisex slides for casual wear and comfort",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "black",
    size_UK: [6, 7, 8, 9],
    price: 30,
    image: "Image_URL_66",
  },
  {
    id: 67,
    gender: "men",
    name: "Nike Air Zoom Structure 24",
    des: "Men's running shoes with stability and support",
    category: "shoes",
    tag: ["Running"],
    color: "grey",
    size_UK: [7, 8, 9, 10],
    price: 140,
    image: "Image_URL_67",
  },
  {
    id: 68,
    gender: "women",
    name: "Nike Blazer Low",
    des: "Women's vintage-style sneakers with suede upper",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "red",
    size_UK: [5, 6, 7, 8],
    price: 100,
    image: "Image_URL_68",
  },
  {
    id: 69,
    gender: "men",
    name: "Nike Air Max Plus",
    des: "Men's athletic shoes with Tuned Air cushioning",
    category: "shoes",
    tag: ["Lifestyle"],
    color: "yellow",
    size_UK: [7, 8, 9, 10],
    price: 170,
    image: "Image_URL_69",
  },
  {
    id: 70,
    gender: "women",
    name: "Nike React Infinity Run Flyknit",
    des: "Women's running shoes with responsive cushioning",
    category: "shoes",
    tag: ["Running"],
    color: "green",
    size_UK: [5, 6, 7, 8],
    price: 160,
    image: "Image_URL_70",
  },
  {
    id: 71,
    gender: "men",
    name: "Nike Air Zoom Alphafly NEXT%",
    des: "Men's professional-grade running shoes for speed",
    category: "shoes",
    tag: ["Running", "Professional"],
    color: "neon",
    size_UK: [7, 8, 9, 10],
    price: 250,
    image: "Image_URL_71",
  },
  {
    id: 72,
    gender: "women",
    name: "Nike Air Zoom Terra Kiger 7",
    des: "Women's trail running shoes with responsive cushioning",
    category: "shoes",
    tag: ["Running", "Trail"],
    color: "purple",
    size_UK: [5, 6, 7, 8],
    price: 210,
    image: "Image_URL_72",
  },
  {
    id: 73,
    gender: "men",
    name: "Nike Mercurial Superfly 8 Elite FG",
    des: "Men's football boots for elite performance",
    category: "shoes",
    tag: ["Football", "Elite"],
    color: "black",
    size_UK: [7, 8, 9, 10],
    price: 280,
    image: "Image_URL_73",
  },
  {
    id: 74,
    gender: "women",
    name: "Nike Air Zoom Tempo NEXT%",
    des: "Women's racing shoes for speed and comfort",
    category: "shoes",
    tag: ["Running", "Racing"],
    color: "white",
    size_UK: [5, 6, 7, 8],
    price: 270,
    image: "Image_URL_74",
  },
  {
    id: 75,
    gender: "men",
    name: "Nike LeBron 18",
    des: "Men's basketball shoes with LeBron James' signature style",
    category: "shoes",
    tag: ["Basketball", "Signature"],
    color: "red",
    size_UK: [7, 8, 9, 10],
    price: 220,
    image: "Image_URL_75",
  },
  {
    id: 76,
    gender: "women",
    name: "Nike Air Max 97",
    des: "Women's lifestyle shoes with iconic design",
    category: "shoes",
    tag: ["Lifestyle", "Iconic"],
    color: "yellow",
    size_UK: [5, 6, 7, 8],
    price: 240,
    image: "Image_URL_76",
  },
  {
    id: 77,
    gender: "men",
    name: "Nike ZoomX Vaporfly NEXT%",
    des: "Men's racing shoes for maximum energy return",
    category: "shoes",
    tag: ["Running", "Racing"],
    color: "volt",
    size_UK: [7, 8, 9, 10],
    price: 275,
    image: "Image_URL_77",
  },
  {
    id: 78,
    gender: "women",
    name: "Nike Air Force 1 Pixel",
    des: "Women's shoes with modern design and lifted sole",
    category: "shoes",
    tag: ["Lifestyle", "Modern"],
    color: "black",
    size_UK: [5, 6, 7, 8],
    price: 210,
    image: "Image_URL_78",
  },
  {
    id: 79,
    gender: "men",
    name: "Nike Air Zoom BB NXT",
    des: "Men's basketball shoes with responsive cushioning",
    category: "shoes",
    tag: ["Basketball", "Cushioned"],
    color: "blue",
    size_UK: [7, 8, 9, 10],
    price: 230,
    image: "Image_URL_79",
  },
  {
    id: 80,
    gender: "women",
    name: "Nike Air Max 2090 EOI",
    des: "Women's lifestyle shoes with futuristic design",
    category: "shoes",
    tag: ["Lifestyle", "Futuristic"],
    color: "grey",
    size_UK: [5, 6, 7, 8],
    price: 250,
    image: "Image_URL_80",
  },
  {
    id: 81,
    gender: "men",
    name: "Nike Air Jordan 1 Retro High OG",
    des: "Men's iconic basketball shoes with retro style",
    category: "shoes",
    tag: ["Basketball", "Jordan", "Lifestyle"],
    color: "black",
    size_UK: [7, 8, 9, 10],
    price: 200,
    image: "Image_URL_81",
  },
  {
    id: 82,
    gender: "women",
    name: "Nike Air Max Verona",
    des: "Women's lifestyle shoes inspired by '90s Air Max",
    category: "shoes",
    tag: ["Lifestyle", "Women's"],
    color: "white",
    size_UK: [5, 6, 7, 8],
    price: 140,
    image: "Image_URL_82",
  },
  {
    id: 83,
    gender: "men",
    name: "Nike React Infinity Run Flyknit",
    des: "Men's cushioned running shoes with React foam",
    category: "shoes",
    tag: ["Running", "Cushioned", "Training & Gym"],
    color: "blue",
    size_UK: [7, 8, 9, 10],
    price: 160,
    image: "Image_URL_83",
  },
  {
    id: 84,
    gender: "women",
    name: "Nike Sportswear Essential Fleece Hoodie",
    des: "Women's fleece hoodie for comfortable wear",
    category: "clothing",
    tag: ["Hoodies & Sweatshirts", "Women's"],
    color: "grey",
    size_UK: ["XS", "S", "M", "L"],
    price: 80,
    image: "Image_URL_84",
  },
  {
    id: 85,
    gender: "men",
    name: "Nike Air Zoom Pegasus 38",
    des: "Men's versatile running shoes with Zoom Air unit",
    category: "shoes",
    tag: ["Running", "Versatile"],
    color: "black",
    size_UK: [7, 8, 9, 10],
    price: 140,
    image: "Image_URL_85",
  },
  {
    id: 86,
    gender: "women",
    name: "Nike Tempo Luxe Running Shorts",
    des: "Women's lightweight running shorts",
    category: "clothing",
    tag: ["Shorts", "Women's", "Running"],
    color: "pink",
    size_UK: ["XS", "S", "M", "L"],
    price: 45,
    image: "Image_URL_86",
  },
  {
    id: 87,
    gender: "men",
    name: "Nike Air Max 270",
    des: "Men's lifestyle shoes with Max Air cushioning",
    category: "shoes",
    tag: ["Lifestyle", "Men's"],
    color: "red",
    size_UK: [7, 8, 9, 10],
    price: 150,
    image: "Image_URL_87",
  },
  {
    id: 88,
    gender: "women",
    name: "Nike One Luxe Tights",
    des: "Women's high-rise tights for versatile wear",
    category: "clothing",
    tag: ["Trousers & Tights", "Women's", "Athletics"],
    color: "black",
    size_UK: ["XS", "S", "M", "L"],
    price: 85,
    image: "Image_URL_88",
  },
  {
    id: 89,
    gender: "men",
    name: "Nike SB Zoom Stefan Janoski RM",
    des: "Men's skateboarding shoes with responsive cushioning",
    category: "shoes",
    tag: ["Skateboarding", "Men's"],
    color: "grey",
    size_UK: [7, 8, 9, 10],
    price: 90,
    image: "Image_URL_89",
  },
  {
    id: 90,
    gender: "women",
    name: "NikeCourt Air Zoom GP Turbo",
    des: "Women's tennis shoes with Zoom Air unit",
    category: "shoes",
    tag: ["Tennis", "Women's"],
    color: "white",
    size_UK: [5, 6, 7, 8],
    price: 170,
    image: "Image_URL_90",
  },
  {
    id: 91,
    gender: "men",
    name: "Nike Air Jordan 4 Retro",
    des: "Men's iconic basketball shoes with classic style",
    category: "shoes",
    tag: ["Basketball", "Jordan", "Lifestyle"],
    color: "black",
    size_UK: [7, 8, 9, 10],
    price: 220,
    image: "Image_URL_91",
  },
  {
    id: 92,
    gender: "women",
    name: "Nike React Infinity Run Flyknit",
    des: "Women's cushioned running shoes with React foam",
    category: "shoes",
    tag: ["Running", "Cushioned", "Training & Gym"],
    color: "pink",
    size_UK: [5, 6, 7, 8],
    price: 230,
    image: "Image_URL_92",
  },
  {
    id: 93,
    gender: "men",
    name: "Nike Mercurial Vapor 14 Elite FG",
    des: "Men's football boots for explosive speed",
    category: "shoes",
    tag: ["Football", "Speed"],
    color: "blue",
    size_UK: [7, 8, 9, 10],
    price: 270,
    image: "Image_URL_93",
  },
  {
    id: 94,
    gender: "women",
    name: "Nike Air Max Furyosa",
    des: "Women's lifestyle shoes with bold design",
    category: "shoes",
    tag: ["Lifestyle", "Bold"],
    color: "purple",
    size_UK: [5, 6, 7, 8],
    price: 250,
    image: "Image_URL_94",
  },
  {
    id: 95,
    gender: "men",
    name: "Nike Air Max 97",
    des: "Men's iconic sneakers with full-length Air unit",
    category: "shoes",
    tag: ["Lifestyle", "Iconic"],
    color: "grey",
    size_UK: [7, 8, 9, 10],
    price: 260,
    image: "Image_URL_95",
  },
  {
    id: 96,
    gender: "women",
    name: "Nike Indy Icon Clash Sports Bra",
    des: "Women's sports bra with light support",
    category: "clothing",
    tag: ["Sports Bras", "Women's"],
    color: "black",
    size_UK: ["XS", "S", "M", "L"],
    price: 45,
    image: "Image_URL_96",
  },
  {
    id: 97,
    gender: "men",
    name: "Nike ZoomX Dragonfly Racing Spike",
    des: "Men's racing spikes for elite track performance",
    category: "shoes",
    tag: ["Running", "Racing", "Track"],
    color: "neon",
    size_UK: [7, 8, 9, 10],
    price: 290,
    image: "Image_URL_97",
  },
  {
    id: 98,
    gender: "women",
    name: "Nike Air Zoom SuperRep 2",
    des: "Women's training shoes for high-intensity workouts",
    category: "shoes",
    tag: ["Training & Gym", "High-Intensity"],
    color: "grey",
    size_UK: [5, 6, 7, 8],
    price: 220,
    image: "Image_URL_98",
  },
  {
    id: 99,
    gender: "men",
    name: "Nike Air Max 90",
    des: "Men's lifestyle shoes with classic design",
    category: "shoes",
    tag: ["Lifestyle", "Classic"],
    color: "white",
    size_UK: [7, 8, 9, 10],
    price: 210,
    image: "Image_URL_99",
  },
  {
    id: 100,
    gender: "women",
    name: "Nike Air Zoom Vomero 16",
    des: "Women's cushioned running shoes for long-distance runs",
    category: "shoes",
    tag: ["Running", "Cushioned", "Long-Distance"],
    color: "blue",
    size_UK: [5, 6, 7, 8],
    price: 240,
    image: "Image_URL_100",
  },
];
export default products;
